language: node_js
cache: 
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
branches: 
  except:
  - main
  only:
  - publicacion
before_script:
  - yarn run env
script:
  - yarn start
notification:
  email:
    recipients:
      - angel.espinozatorres213@gmail.com
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  skip-cleanup: true
  keep-history: true
  #esta api key nos la proveera heroku
  api_key: $API_KEY_HEROKU
  #este es el nombre del api del proyecto, en nuestro caso es el de heroku
  app: capacisoftapi
  #en este segmento indicamos donde esta alojado el proyecto
  on:
    repo: AngelCertificatedProfessional/CapacisoftAPI
env:
  - DB_MONGO=test